apiVersion: v1
kind: Service
metadata:
  name: {{ include "node-io-manager.fullname" . }}
  labels:
    {{- include "node-io-manager.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.config.apiPort }}
      targetPort: api
      protocol: TCP
      name: api
    - port: {{ .Values.config.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "node-io-manager.selectorLabels" . | nindent 4 }}
